name: Heroku Scheduled Job

on:
  schedule:
    - cron: '*/5 * * * *'  # 5分毎に実行

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    # - name: Log in to Heroku
    #   env:
    #     HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    #   run: |
    #     echo $HEROKU_API_KEY | heroku login -i

    - name: Run command
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: sendsintyaku2
      run: |
        heroku run --app $HEROKU_APP_NAME -- python send.py