name: Heroku Scheduled Job

on:
  schedule:
    - cron: '0 10 * * *'  # 5分ごとに実行

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # お使いのPythonバージョンに合わせてください

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psycopg2-binary requests line-bot-sdk

    - name: Run script
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
      run: |
        python send.py