name: Heroku Scheduled Job

on:
  schedule:
    - cron: '*/5 * * * *' 

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    - name: Log in to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku auth:token

    - name: Run command
      env:
        HEROKU_APP_NAME: sendsintyaku
      run: |
        heroku run python send.py --app $HEROKU_APP_NAME